export const SELECT_ARTICLE = 'SELECT_ARTICLE';
export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const RECEIVE_ARTICLES = 'RECEIVE_ARTICLES';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const DELETE_ARTICLE_COMPLETE = 'DELETE_ARTICLE_COMPLETE';

export const PLAY = 'PLAY';
export const PAUSE = 'PAUSE';
export const STOP = 'STOP';
export const LOAD_TRACK = 'LOAD_TRACK';
export const RECEIVE_TRACK = 'RECEIVE_TRACK';
export const RECEIVE_PROGRESS = 'RECEIVE_PORGRESS';
export const RESET_PLAYER = 'RESET_PLAYER';

export const CHANGE_TITLE = 'CHANGE_TITLE';
export const SUBMIT_REQUEST = 'SUBMIT_REQUEST';
export const SUBMIT_COMPLETE = 'SUBMIT_COMPLETE';
export const RESET_FORM = 'RESET_FORM';
export const RECEIVE_AUDIO = 'RECEIVE_AUDIO';

export const START_RECORDING = 'START_RECORDING';
export const STOP_RECORDING = 'STOP_RECORDING';
export const RESET_RECORDER = 'RESET_RECORDER';

export const REQUEST_MIC_PERMISSION = 'REQUEST_MIC_PERMISSION';
export const MIC_PREMISSION_SUCCESS = 'MIC_PREMIT_SUCCESS';
export const PREMISSION_DENIED = 'PREMIT_DENIED';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
